WINDOW_TITLE = 'Power predictor'
WINDOW_SIZE = '370x320'
FONT = 'Arial, 12'

WS_LABEL = 'Wind'
RM_LABEL = 'Torque'
CM_LABEL = 'Converter torque'
RS_LABEL = 'Rotor speed'
P_LABEL = 'P = '

PREDICT_BUTTON_TEXT = 'Predict'
SELECT_FILE_BUTTON_TEXT = 'Select file'

ROW_INTERVAL = 40
LABEL_X = 30
ENTRY_X = 150

SELECT_FILE_BUTTON_LEFT = 40
PREDICT_BUTTON_LEFT = 200
BUTTON_TOP = 250

BUTTON_WIDTH = 11
BUTTON_HEIGHT = 1

WS_ORDER = 0
RM_ORDER = 1
CM_ORDER = 2
RS_ORDER = 3
P_ORDER = 4

CLUSTER_NUMBER = 3

MACHINE_ATTR_NAME = 'Wind_turbine_name'
WS_ATTR_NAME = 'Ws'
RM_ATTR_NAME = 'Rm'
CM_ATTR_NAME = 'Cm'
RS_ATTR_NAME = 'Rs'
P_ATTR_NAME = 'P'

ATTRS_NAME = ['Ws', 'Rm', 'Cm', 'Rs', 'P']


DF_HELPER_TYPE_ERROR = 'df_helper must be DFHelper'
